name: Feature Request 🙏
description: Suggest a new feature or enhancement
title: "Category: Short feature description (PLEASE CHANGE)"
labels:
  - idea
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Before submitting a new feature request, please [review our public roadmap](https://link.photoprism.app/roadmap) and [search GitHub for similar requests](https://github.com/photoprism/photoprism/issues).
  - type: checkboxes
    id: request-prep
    attributes:
      label: Confirmation
      description: Make sure you completed these steps before opening a new request.
      options:
        - label: I confirm that this request is not a support question and that I searched the roadmap and existing issues.
          required: true
  - type: textarea
    id: problem-statement
    attributes:
      label: What Problem Does This Solve and Why Is It Valuable?
      description: Explain the underlying problem and why solving it matters to many users.
      placeholder: Describe the problem, why it is important, and who is affected.
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: What Solution Would You Like?
      description: Provide a clear and concise description of the feature or enhancement you propose.
      placeholder: Outline the proposed solution or experience from the user's perspective.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: What Alternatives Have You Considered?
      description: Describe other options you explored and why they are less suitable.
      placeholder: Mention any alternative solutions, workarounds, or related features you evaluated.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Share relevant context, references, or screenshots that illustrate the request.
      placeholder: Add links, references, or screenshots that help explain the request.
