name: Question 💬
description: Use Discussions for general questions, community support, and troubleshooting help
title: "Category: Question details (PLEASE CHANGE)"
labels:
  - question
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use Discussions for general questions, community support, and troubleshooting help:
        https://github.com/photoprism/photoprism/discussions
  - type: checkboxes
    id: question-confirmation
    attributes:
      label: Please Confirm
      options:
        - label: I understand that questions should not be asked through GitHub Issues
          required: true
  - type: textarea
    id: your-question
    attributes:
      label: Your Question
      description: Provide the specific question and the context needed to answer it.
      placeholder: Summarize your question, the context, and any resources you have already reviewed.
    validations:
      required: true
