name: Question
description: General questions or assistance requests should go to Discussions or community channels
title: "Category: Short Description (PLEASE CHANGE)"
labels:
  - question
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        FOR GENERAL QUESTIONS, TECHNICAL SUPPORT, AND TO GET TO KNOW OTHER COMMUNITY MEMBERS, VISIT https://github.com/photoprism/photoprism/discussions.
        OUR TROUBLESHOOTING CHECKLISTS HELP YOU QUICKLY DIAGNOSE AND FIX COMMON PROBLEMS: https://docs.photoprism.app/getting-started/troubleshooting/.
        PLEASE DO NOT OPEN AN ISSUE FOR YOUR QUESTION, AND USE GITHUB DISCUSSIONS OR OUR COMMUNITY CHAT INSTEAD. THANK YOU VERY MUCH!
  - type: checkboxes
    id: question-confirmation
    attributes:
      label: Please Confirm
      options:
        - label: I understand that general questions should be posted in Discussions or community chat, and I still need to open an issue here.
          required: true
  - type: textarea
    id: question-details
    attributes:
      label: Question Details
      description: Provide the specific question and the context needed to answer it.
      placeholder: Summarize your question, the context, and any resources you have already reviewed.
    validations:
      required: true
